from __future__ import annotations

"""Verify ClassicBar standalone icon placeholders.

These placeholder icons are generated by this repository's own scripts and are
not extracted from Minecraft or third-party mods.

Compat fallback icons (blood/thirst/stamina/feathers) are reserved placeholder
files only. Their presence keeps stable replacement paths available while the
corresponding compat overlays remain quarantined; it does not mean compat
support has been restored.
"""

import re
import struct
import sys
import zlib
from pathlib import Path, PurePosixPath


ROOT = Path(__file__).resolve().parent.parent
ACTIVE_OVERLAYS = {
    "health": "HEALTH",
    "armor": "ARMOR",
    "absorption": "ABSORPTION",
    "food": "FOOD",
    "armor_toughness": "ARMOR_TOUGHNESS",
    "health_mount": "MOUNT_HEALTH",
    "air": "AIR",
}
ACTIVE_VANILLA_OVERLAY_FILES = {
    "health": ROOT / "src" / "main" / "java" / "tfar" / "classicbar" / "impl" / "overlays" / "vanilla" / "Health.java",
    "armor": ROOT / "src" / "main" / "java" / "tfar" / "classicbar" / "impl" / "overlays" / "vanilla" / "Armor.java",
    "absorption": ROOT / "src" / "main" / "java" / "tfar" / "classicbar" / "impl" / "overlays" / "vanilla" / "Absorption.java",
    "food": ROOT / "src" / "main" / "java" / "tfar" / "classicbar" / "impl" / "overlays" / "vanilla" / "Hunger.java",
    "armor_toughness": ROOT / "src" / "main" / "java" / "tfar" / "classicbar" / "impl" / "overlays" / "vanilla" / "ArmorToughness.java",
    "health_mount": ROOT / "src" / "main" / "java" / "tfar" / "classicbar" / "impl" / "overlays" / "vanilla" / "MountHealth.java",
    "air": ROOT / "src" / "main" / "java" / "tfar" / "classicbar" / "impl" / "overlays" / "vanilla" / "Air.java",
}
REQUIRED_ICON_FILES = [
    "fallback",
    "health",
    "armor",
    "food",
    "air",
    "absorption",
    "armor_toughness",
    "mount_health",
]
COMPAT_ICON_FILES = {
    "blood": "BLOOD",
    "thirst": "THIRST",
    "stamina": "STAMINA",
    "feathers": "FEATHERS",
}
FORBIDDEN_ICON_SOURCES = [
    'fromNamespaceAndPath("minecraft", "textures/gui/icons.png")',
    'fromNamespaceAndPath("vampirism", "textures/gui/icons.png")',
    'fromNamespaceAndPath("toughasnails", "textures/gui/icons.png")',
    'fromNamespaceAndPath("parcool", "textures/gui/stamina_bar.png")',
]
PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
SUPPORTED_ALPHA_COLOR_TYPES = {4, 6}
FORBIDDEN_ACTIVE_ICON_REFERENCES = [
    'minecraft:',
    'textures/gui/icons.png',
    'InventoryMenu',
    'TextureAtlas',
    'graphics.blit(',
    'drawTexturedModalRect',
]


class CheckContext:
    def __init__(self) -> None:
        self.failures: list[str] = []
        self.notes: list[str] = []

    def fail(self, message: str) -> None:
        self.failures.append(message)

    def note(self, message: str) -> None:
        self.notes.append(message)


def read_text(path: Path, ctx: CheckContext) -> str:
    if not path.exists():
        ctx.fail(f"Missing required file: {path.relative_to(ROOT)}")
        return ""
    return path.read_text(encoding="utf-8")


def require_regex(text: str, pattern: str, label: str, ctx: CheckContext) -> None:
    if re.search(pattern, text, flags=re.MULTILINE) is None:
        ctx.fail(f"{label}: expected pattern {pattern!r}")


def require_contains(text: str, needle: str, label: str, ctx: CheckContext) -> None:
    if needle not in text:
        ctx.fail(f"{label}: expected to contain {needle!r}")


def method_body(text: str, signature: str) -> str:
    pattern = re.compile(rf"{re.escape(signature)}[^{{]*\{{(?P<body>.*?)\n\s*\}}", flags=re.DOTALL)
    match = pattern.search(text)
    return match.group("body") if match else ""


def extract_source_set_excludes(build_gradle: str) -> list[str]:
    return re.findall(r"exclude\s+'([^']+)'", build_gradle)


def path_matches_any(path: str, patterns: list[str]) -> bool:
    posix_path = PurePosixPath(path)
    return any(posix_path.match(pattern) for pattern in patterns)


def collect_java_matches(root: Path, needle: str) -> list[str]:
    matches: list[str] = []
    for file in root.rglob("*.java"):
        text = file.read_text(encoding="utf-8")
        if needle in text:
            matches.append(file.relative_to(ROOT).as_posix())
    return sorted(matches)


def active_matches(matches: list[str], allowlist: list[str]) -> list[str]:
    active: list[str] = []
    for path in matches:
        relative_java_path = path.replace("src/main/java/", "")
        if not path_matches_any(relative_java_path, allowlist):
            active.append(path)
    return active


def check_png(path: Path, ctx: CheckContext) -> None:
    if not path.exists():
        ctx.fail(f"Missing icon file: {path.relative_to(ROOT)}")
        return
    data = path.read_bytes()
    if not data:
        ctx.fail(f"Empty icon file: {path.relative_to(ROOT)}")
        return
    if not data.startswith(PNG_SIGNATURE):
        ctx.fail(f"Invalid PNG signature: {path.relative_to(ROOT)}")
        return

    try:
        info = inspect_png(data)
    except ValueError as exc:
        ctx.fail(f"{path.relative_to(ROOT)}: {exc}")
        return

    if info["width"] != 9 or info["height"] != 9:
        ctx.fail(
            f"{path.relative_to(ROOT)}: expected 9x9 icon canvas, got {info['width']}x{info['height']}"
        )
    if info["color_type"] not in SUPPORTED_ALPHA_COLOR_TYPES:
        ctx.fail(
            f"{path.relative_to(ROOT)}: expected PNG color type with explicit alpha support (4 or 6), got {info['color_type']}"
        )
    if info["bit_depth"] != 8:
        ctx.fail(f"{path.relative_to(ROOT)}: expected 8-bit placeholder PNG, got bit depth {info['bit_depth']}")
    if not info["has_transparent_pixel"]:
        ctx.fail(f"{path.relative_to(ROOT)}: expected at least one transparent pixel")
    if not info["has_opaque_pixel"]:
        ctx.fail(f"{path.relative_to(ROOT)}: expected at least one non-transparent pixel")


def inspect_png(data: bytes) -> dict[str, int | bool]:
    if len(data) < len(PNG_SIGNATURE):
        raise ValueError("truncated PNG signature")

    offset = len(PNG_SIGNATURE)
    ihdr: dict[str, int] | None = None
    idat_parts: list[bytes] = []
    saw_iend = False

    while offset < len(data):
        if offset + 8 > len(data):
            raise ValueError("truncated PNG chunk header")

        length = struct.unpack(">I", data[offset:offset + 4])[0]
        chunk_type = data[offset + 4:offset + 8]
        data_start = offset + 8
        data_end = data_start + length
        crc_end = data_end + 4

        if crc_end > len(data):
            raise ValueError(f"truncated PNG chunk payload for {chunk_type.decode('latin1')}")

        chunk_data = data[data_start:data_end]
        offset = crc_end

        if ihdr is None:
            if chunk_type != b"IHDR":
                raise ValueError("PNG missing leading IHDR chunk")
            if length != 13:
                raise ValueError("IHDR chunk has invalid length")
            width, height, bit_depth, color_type, compression, filter_method, interlace = struct.unpack(
                ">IIBBBBB", chunk_data
            )
            if compression != 0:
                raise ValueError(f"unsupported PNG compression method {compression}")
            if filter_method != 0:
                raise ValueError(f"unsupported PNG filter method {filter_method}")
            if interlace != 0:
                raise ValueError("interlaced PNG placeholders are not supported")
            ihdr = {
                "width": width,
                "height": height,
                "bit_depth": bit_depth,
                "color_type": color_type,
            }
        elif chunk_type == b"IDAT":
            idat_parts.append(chunk_data)
        elif chunk_type == b"IEND":
            saw_iend = True
            break

    if ihdr is None:
        raise ValueError("PNG missing IHDR chunk")
    if not idat_parts:
        raise ValueError("PNG missing IDAT chunk")
    if not saw_iend:
        raise ValueError("PNG missing IEND chunk")
    if offset != len(data):
        raise ValueError("PNG contains trailing bytes after IEND")
    if ihdr["bit_depth"] != 8:
        raise ValueError(f"unsupported PNG bit depth {ihdr['bit_depth']}; expected 8-bit placeholders")
    if ihdr["color_type"] not in SUPPORTED_ALPHA_COLOR_TYPES:
        raise ValueError(
            f"unsupported PNG color type {ihdr['color_type']}; expected explicit alpha color type 4 or 6"
        )

    inflated = zlib.decompress(b"".join(idat_parts))
    channels = {4: 2, 6: 4}[ihdr["color_type"]]
    bytes_per_pixel = channels
    stride = ihdr["width"] * bytes_per_pixel
    expected_size = (stride + 1) * ihdr["height"]
    if len(inflated) != expected_size:
        raise ValueError(
            f"unexpected decompressed PNG payload length {len(inflated)}; expected {expected_size}"
        )

    has_transparent_pixel = False
    has_opaque_pixel = False
    previous = bytearray(stride)
    cursor = 0
    for _ in range(ihdr["height"]):
        filter_type = inflated[cursor]
        cursor += 1
        encoded = inflated[cursor:cursor + stride]
        cursor += stride
        row = unfilter_scanline(filter_type, encoded, previous, bytes_per_pixel)
        alpha_index = bytes_per_pixel - 1
        for pixel_start in range(0, stride, bytes_per_pixel):
            alpha = row[pixel_start + alpha_index]
            if alpha == 0:
                has_transparent_pixel = True
            if alpha > 0:
                has_opaque_pixel = True
        previous = row

    return {
        **ihdr,
        "has_transparent_pixel": has_transparent_pixel,
        "has_opaque_pixel": has_opaque_pixel,
    }


def unfilter_scanline(filter_type: int, encoded: bytes, previous: bytearray, bytes_per_pixel: int) -> bytearray:
    row = bytearray(len(encoded))
    if filter_type == 0:
        row[:] = encoded
        return row

    for index, value in enumerate(encoded):
        left = row[index - bytes_per_pixel] if index >= bytes_per_pixel else 0
        up = previous[index] if previous else 0
        upper_left = previous[index - bytes_per_pixel] if previous and index >= bytes_per_pixel else 0

        if filter_type == 1:
            row[index] = (value + left) & 0xFF
        elif filter_type == 2:
            row[index] = (value + up) & 0xFF
        elif filter_type == 3:
            row[index] = (value + ((left + up) // 2)) & 0xFF
        elif filter_type == 4:
            row[index] = (value + paeth(left, up, upper_left)) & 0xFF
        else:
            raise ValueError(f"unsupported PNG filter type {filter_type}")

    return row


def paeth(left: int, up: int, upper_left: int) -> int:
    predictor = left + up - upper_left
    left_distance = abs(predictor - left)
    up_distance = abs(predictor - up)
    upper_left_distance = abs(predictor - upper_left)
    if left_distance <= up_distance and left_distance <= upper_left_distance:
        return left
    if up_distance <= upper_left_distance:
        return up
    return upper_left


def required_compat_icons(bar_icons: str, classic_bars_config: str) -> list[str]:
    required: list[str] = []
    for overlay_name, constant in COMPAT_ICON_FILES.items():
        if f'case "{overlay_name}"' in bar_icons or f"BarIcons.{constant}" in classic_bars_config:
            required.append(overlay_name)
    return required


def main() -> int:
    ctx = CheckContext()

    build_gradle = read_text(ROOT / "build.gradle", ctx)
    classic_bars_config = read_text(ROOT / "src" / "main" / "java" / "tfar" / "classicbar" / "config" / "ClassicBarsConfig.java", ctx)
    mod_utils = read_text(ROOT / "src" / "main" / "java" / "tfar" / "classicbar" / "util" / "ModUtils.java", ctx)
    bar_overlay_impl = read_text(ROOT / "src" / "main" / "java" / "tfar" / "classicbar" / "impl" / "BarOverlayImpl.java", ctx)
    bar_overlay_api = read_text(ROOT / "src" / "main" / "java" / "tfar" / "classicbar" / "api" / "BarOverlay.java", ctx)
    bar_icons = read_text(ROOT / "src" / "main" / "java" / "tfar" / "classicbar" / "resources" / "BarIcons.java", ctx)

    quarantine_allowlist = extract_source_set_excludes(build_gradle)
    if not quarantine_allowlist:
        ctx.fail("build.gradle: expected sourceSets quarantine excludes for Phase 2")

    for forbidden in FORBIDDEN_ICON_SOURCES:
        matches = collect_java_matches(ROOT / "src" / "main" / "java", forbidden)
        active = active_matches(matches, quarantine_allowlist)
        if active:
            ctx.fail(f"Active compiled sources still reference forbidden icon source {forbidden!r}: {', '.join(active)}")
        elif matches:
            ctx.note(f"Forbidden icon source {forbidden!r} only remains in quarantined sources: {', '.join(matches)}")

    require_regex(classic_bars_config, r'displayIcons\s*=\s*builder(?:.|\n)*?define\("display_icons",\s*true\)', "ClassicBarsConfig display_icons default", ctx)
    if "BarIcons.FALLBACK" not in classic_bars_config:
        ctx.fail("ClassicBarsConfig fallback icon: expected ClassicBar-owned fallback icon default")

    for overlay, constant in ACTIVE_OVERLAYS.items():
        require_contains(bar_icons, f"public static final ResourceLocation {constant}", "BarIcons active constants", ctx)
        require_contains(classic_bars_config, f"BarIcons.{constant}", f"ClassicBarsConfig default icon for {overlay}", ctx)

    require_contains(bar_icons, 'textures/gui/icons/" + name + ".png"', "BarIcons stable icon file path", ctx)
    require_contains(classic_bars_config, 'ClassicBar.MODID.equals(resourceLocation.getNamespace())', "ClassicBarsConfig icon namespace validator", ctx)
    require_contains(classic_bars_config, 'resourceLocation.getPath().startsWith("textures/gui/icons/")', "ClassicBarsConfig icon path prefix validator", ctx)
    require_contains(classic_bars_config, 'resourceLocation.getPath().endsWith(".png")', "ClassicBarsConfig icon suffix validator", ctx)

    for overlay in REQUIRED_ICON_FILES:
        icon_path = ROOT / "src" / "main" / "resources" / "assets" / "classicbar" / "textures" / "gui" / "icons" / f"{overlay}.png"
        check_png(icon_path, ctx)

    compat_icons = required_compat_icons(bar_icons, classic_bars_config)
    if compat_icons:
        ctx.note(
            "Compat fallback placeholders remain referenced and therefore required: "
            + ", ".join(f"{name}.png" for name in compat_icons)
        )
        ctx.note(
            "Compat fallback placeholders are reserved replacement targets only; they do not indicate compat support is restored."
        )
        for overlay in compat_icons:
            icon_path = ROOT / "src" / "main" / "resources" / "assets" / "classicbar" / "textures" / "gui" / "icons" / f"{overlay}.png"
            check_png(icon_path, ctx)

    require_contains(mod_utils, "CURRENT_TEXTURE = BarIcons.FALLBACK", "ModUtils fallback current texture", ctx)
    require_contains(mod_utils, "drawStandaloneIcon", "ModUtils standalone icon helper", ctx)
    require_contains(bar_overlay_impl, '"textures/gui/health.png"', "BarOverlayImpl bar texture reuse stays allowed", ctx)
    require_contains(bar_overlay_api, "ModUtils.CURRENT_TEXTURE = getIconRL();", "BarOverlay bindIconTexture", ctx)
    require_regex(
        bar_overlay_impl,
        r'if \(shouldRenderText\(\)\) \{\s*Color\.reset\(\);\s*renderText\(',
        "BarOverlayImpl reset before renderText",
        ctx,
    )
    require_regex(
        bar_overlay_impl,
        r'if \(ConfigCache\.icons\) \{\s*Color\.reset\(\);\s*bindIconTexture\(\);\s*renderIcon\(',
        "BarOverlayImpl reset before renderIcon",
        ctx,
    )

    for overlay_name, overlay_file in ACTIVE_VANILLA_OVERLAY_FILES.items():
        text = read_text(overlay_file, ctx)
        body = method_body(text, "public void renderIcon")
        if not body:
            ctx.fail(f"{overlay_file.relative_to(ROOT).as_posix()}: missing renderIcon method")
            continue
        require_contains(body, "ModUtils.drawStandaloneIcon", f"{overlay_name} renderIcon uses standalone icon", ctx)
        for forbidden in FORBIDDEN_ACTIVE_ICON_REFERENCES:
            if forbidden in body:
                ctx.fail(f"{overlay_file.relative_to(ROOT).as_posix()}: renderIcon should not contain {forbidden!r}")

    if ctx.failures:
        print("Independent icon verification: RED")
        for failure in ctx.failures:
            print(f"- {failure}")
        if ctx.notes:
            print("\nNotes:")
            for note in ctx.notes:
                print(f"- {note}")
        return 1

    print("Independent icon verification: GREEN")
    for note in ctx.notes:
        print(f"- {note}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
